"use strict";
// cities.ts
// Configuration file for cities organized by location type
Object.defineProperty(exports, "__esModule", { value: true });
exports.CITIES_NOT_BY_WATER = exports.CITIES_BY_WATER = void 0;
exports.CITIES_BY_WATER = [
    { name: "London", slug: "london" },
    { name: "New York", slug: "new-york" },
    { name: "Dubai", slug: "dubai" },
    { name: "Singapore", slug: "singapore" },
    { name: "Barcelona", slug: "barcelona" },
    { name: "Istanbul", slug: "istanbul" },
    { name: "Los Angeles", slug: "los-angeles" },
    { name: "Hong Kong", slug: "hong-kong" },
    { name: "Miami", slug: "miami" },
    { name: "San Francisco", slug: "san-francisco" },
    { name: "Amsterdam", slug: "amsterdam" },
    { name: "Sydney", slug: "sydney" },
    { name: "Lisbon", slug: "lisbon" },
    { name: "Chicago", slug: "chicago" },
    { name: "Venice", slug: "venice" },
    { name: "Melbourne", slug: "melbourne" },
    { name: "Boston", slug: "boston" },
    { name: "Toronto", slug: "toronto" },
    { name: "San Diego", slug: "san-diego" },
    { name: "Athens", slug: "athens" },
    { name: "Dublin", slug: "dublin" },
    { name: "Rio de Janeiro", slug: "rio-de-janeiro" },
    { name: "Cancun", slug: "cancun" },
    { name: "Shanghai", slug: "shanghai" },
    { name: "Abu Dhabi", slug: "abu-dhabi" },
    { name: "Antalya", slug: "antalya" },
    { name: "Copenhagen", slug: "copenhagen" },
    { name: "Stockholm", slug: "stockholm" },
    { name: "Vancouver", slug: "vancouver" },
    { name: "San Juan", slug: "san-juan" },
    { name: "Monaco", slug: "monaco" },
    { name: "Nice", slug: "nice" },
    { name: "Ibiza", slug: "ibiza" },
    { name: "Phuket", slug: "phuket" },
    { name: "Santorini", slug: "santorini" },
    { name: "Mykonos", slug: "mykonos" },
    { name: "Palma de Mallorca", slug: "palma-de-mallorca" },
    { name: "Bali", slug: "bali" },
    { name: "Honolulu", slug: "honolulu" },
    { name: "Maui", slug: "maui" },
    { name: "Ohau", slug: "ohau" },
    { name: "Reykjavik", slug: "reykjavik" },
    { name: "Auckland", slug: "auckland" },
    { name: "Brisbane", slug: "brisbane" },
    { name: "Wellington", slug: "wellington" },
    { name: "Ho Chi Minh City", slug: "ho-chi-minh-city" },
    { name: "Cartagena", slug: "cartagena" },
    { name: "Havana", slug: "havana" },
    { name: "Puerto Vallarta", slug: "puerto-vallarta" },
    { name: "Acapulco", slug: "acapulco" },
    { name: "Punta Cana", slug: "punta-cana" },
    { name: "Cozumel", slug: "cozumel" },
    { name: "Playa del Carmen", slug: "playa-del-carmen" },
    { name: "Montego Bay", slug: "montego-bay" },
    { name: "Ocho Rios", slug: "ocho-rios" },
    { name: "Varadero", slug: "varadero" },
    { name: "Male", slug: "male" },
    { name: "Phuket Town", slug: "phuket-town" },
    { name: "Krabi", slug: "krabi" },
    { name: "Koh Samui", slug: "koh-samui" },
    { name: "Bora Bora", slug: "bora-bora" },
    { name: "Bodrum", slug: "bodrum" },
    { name: "Dubrovnik", slug: "dubrovnik" },
    { name: "Split", slug: "split" },
    { name: "Kotor", slug: "kotor" },
    { name: "Corfu", slug: "corfu" },
    { name: "Rhodes", slug: "rhodes" },
    { name: "Taormina", slug: "taormina" },
    { name: "Amalfi", slug: "amalfi" },
    { name: "Sorrento", slug: "sorrento" },
    { name: "Porto", slug: "porto" },
    { name: "Valencia", slug: "valencia" },
    { name: "Bilbao", slug: "bilbao" },
    { name: "San Sebastian", slug: "san-sebastian" },
    { name: "Marseille", slug: "marseille" },
    { name: "Naples", slug: "naples" },
    { name: "Palermo", slug: "palermo" },
    { name: "Catania", slug: "catania" },
    { name: "Santiago de Cuba", slug: "santiago-de-cuba" },
    { name: "St. Thomas", slug: "st-thomas" },
    { name: "St. Croix", slug: "st-croix" },
    { name: "St. John's", slug: "st-johns" },
    { name: "Bridgetown", slug: "bridgetown" },
    { name: "Castries", slug: "castries" },
    { name: "Port of Spain", slug: "port-of-spain" },
    { name: "Basseterre", slug: "basseterre" },
    { name: "Philipsburg", slug: "philipsburg" },
    { name: "Charlotte Amalie", slug: "charlotte-amalie" },
    { name: "Oranjestad", slug: "oranjestad" },
    { name: "Willemstad", slug: "willemstad" },
    { name: "Kralendijk", slug: "kralendijk" },
    { name: "Fort Lauderdale", slug: "fort-lauderdale" },
    { name: "Key West", slug: "key-west" },
    { name: "Galveston", slug: "galveston" },
    { name: "Corpus Christi", slug: "corpus-christi" },
    { name: "Charleston", slug: "charleston" },
    { name: "Savannah", slug: "savannah" },
    { name: "Myrtle Beach", slug: "myrtle-beach" },
    { name: "Virginia Beach", slug: "virginia-beach" },
    { name: "Norfolk", slug: "norfolk" },
    { name: "Atlantic City", slug: "atlantic-city" },
    { name: "Halifax", slug: "halifax" },
    { name: "Juneau", slug: "juneau" },
    { name: "Anchorage", slug: "anchorage" },
    { name: "Ketchikan", slug: "ketchikan" },
    { name: "Sitka", slug: "sitka" },
    { name: "Tallinn", slug: "tallinn" },
    { name: "Gdansk", slug: "gdansk" },
    { name: "Biarritz", slug: "biarritz" },
    { name: "Cannes", slug: "cannes" },
    { name: "St. Tropez", slug: "st-tropez" },
    { name: "Lagos", slug: "lagos" },
    { name: "Faro", slug: "faro" },
    { name: "Larnaca", slug: "larnaca" },
    { name: "Limassol", slug: "limassol" },
    { name: "Ajaccio", slug: "ajaccio" },
    { name: "Cagliari", slug: "cagliari" },
    { name: "Madeira", slug: "madeira" },
    { name: "Tenerife", slug: "tenerife" },
    { name: "Gran Canaria", slug: "gran-canaria" },
    { name: "Lanzarote", slug: "lanzarote" },
    { name: "La Coruña", slug: "la-coruna" },
    { name: "Vigo", slug: "vigo" },
    { name: "Menorca", slug: "menorca" },
    { name: "Cadiz", slug: "cadiz" },
    { name: "Gijón", slug: "gijon" },
    { name: "La Rochelle", slug: "la-rochelle" },
    { name: "Saint-Malo", slug: "saint-malo" },
    { name: "Honfleur", slug: "honfleur" },
    { name: "Le Havre", slug: "le-havre" },
    { name: "Cherbourg", slug: "cherbourg" },
    { name: "Calais", slug: "calais" },
    { name: "Dieppe", slug: "dieppe" },
    { name: "Toulon", slug: "toulon" },
    { name: "Dunkirk", slug: "dunkirk" },
    { name: "Brighton", slug: "brighton" },
    { name: "Southampton", slug: "southampton" },
    { name: "Liverpool", slug: "liverpool" },
    { name: "Belfast", slug: "belfast" },
    { name: "Patras", slug: "patras" },
    { name: "Thessaloniki", slug: "thessaloniki" },
    { name: "Chania", slug: "chania" },
    { name: "Izmir", slug: "izmir" },
    { name: "Fethiye", slug: "fethiye" },
    { name: "Marmaris", slug: "marmaris" },
    { name: "Batumi", slug: "batumi" },
    { name: "Sochi", slug: "sochi" },
    { name: "Haifa", slug: "haifa" },
    { name: "Eilat", slug: "eilat" },
    { name: "Muscat", slug: "muscat" },
    { name: "Salalah", slug: "salalah" },
    { name: "Manama", slug: "manama" },
    { name: "Jeddah", slug: "jeddah" },
    { name: "Alexandria", slug: "alexandria" },
    { name: "Casablanca", slug: "casablanca" },
    { name: "Cape Town", slug: "cape-town" },
    { name: "Durban", slug: "durban" },
    { name: "Mombasa", slug: "mombasa" },
    { name: "Zanzibar City", slug: "zanzibar-city" },
    { name: "Stone Town", slug: "stone-town" },
    { name: "Dar es Salaam", slug: "dar-es-salaam" },
    { name: "Maputo", slug: "maputo" },
    { name: "Luanda", slug: "luanda" },
    { name: "Accra", slug: "accra" },
    { name: "Abidjan", slug: "abidjan" },
    { name: "Dakar", slug: "dakar" },
    { name: "Sharm El Sheikh", slug: "sharm-el-sheikh" },
    { name: "Hurghada", slug: "hurghada" },
    { name: "Goa", slug: "goa" },
    { name: "Kochi", slug: "kochi" },
    { name: "Chennai", slug: "chennai" },
    { name: "Mumbai", slug: "mumbai" },
    { name: "Kolkata", slug: "kolkata" },
    { name: "Penang", slug: "penang" },
    { name: "Langkawi", slug: "langkawi" },
    { name: "Kota Kinabalu", slug: "kota-kinabalu" },
    { name: "Cebu City", slug: "cebu-city" },
    { name: "Boracay", slug: "boracay" },
    { name: "Nha Trang", slug: "nha-trang" },
    { name: "Vung Tau", slug: "vung-tau" },
    { name: "Busan", slug: "busan" },
    { name: "Fukuoka", slug: "fukuoka" },
    { name: "Nagasaki", slug: "nagasaki" },
    { name: "Kobe", slug: "kobe" },
    { name: "Hakodate", slug: "hakodate" },
    { name: "Vladivostok", slug: "vladivostok" },
    { name: "Suva", slug: "suva" },
    { name: "Nadi", slug: "nadi" },
    { name: "Papeete", slug: "papeete" },
    { name: "Apia", slug: "apia" },
    { name: "Noumea", slug: "noumea" },
    { name: "Port Louis", slug: "port-louis" },
    { name: "Victoria", slug: "victoria" },
    { name: "George Town", slug: "george-town" },
    { name: "Panama City", slug: "panama-city" },
    { name: "Panama", slug: "panama" },
    { name: "Bahamas", slug: "bahamas" },
    { name: "Shenzhen", slug: "shenzhen" },
    { name: "Seattle", slug: "seattle" },
    { name: "Baltimore", slug: "baltimore" },
    { name: "Tampa", slug: "tampa" },
    { name: "New Orleans", slug: "new-orleans" },
    { name: "Guayaquil", slug: "guayaquil" },
    { name: "Genoa", slug: "genoa" },
    { name: "Valletta", slug: "valletta" },
    { name: "Oslo", slug: "oslo" },
    { name: "Kuwait City", slug: "kuwait-city" },
    { name: "Macau", slug: "macau" },
    { name: "Helsinki", slug: "helsinki" },
    { name: "Rotterdam", slug: "rotterdam" },
    { name: "Hamburg", slug: "hamburg" },
    { name: "Tripoli", slug: "tripoli" },
    { name: "Tunis", slug: "tunis" },
    { name: "Algiers", slug: "algiers" },
    { name: "Oran", slug: "oran" },
    { name: "Tangier", slug: "tangier" },
    { name: "Agadir", slug: "agadir" },
    { name: "Ashdod", slug: "ashdod" },
    { name: "Aqaba", slug: "aqaba" },
    { name: "Port Said", slug: "port-said" },
    { name: "Odessa", slug: "odessa" },
    { name: "Sevastopol", slug: "sevastopol" },
    { name: "Yalta", slug: "yalta" },
    { name: "Novorossiysk", slug: "novorossiysk" },
    { name: "Santa Cruz", slug: "santa-cruz" },
];
exports.CITIES_NOT_BY_WATER = [
    { name: "Paris", slug: "paris" },
    { name: "Rome", slug: "rome" },
    { name: "Tokyo", slug: "tokyo" },
    { name: "Bangkok", slug: "bangkok" },
    { name: "Orlando", slug: "orlando" },
    { name: "Las Vegas", slug: "las-vegas" },
    { name: "Kyoto", slug: "kyoto" },
    { name: "Florence", slug: "florence" },
    { name: "Madrid", slug: "madrid" },
    { name: "Milan", slug: "milan" },
    { name: "Vienna", slug: "vienna" },
    { name: "Prague", slug: "prague" },
    { name: "Berlin", slug: "berlin" },
    { name: "Buenos Aires", slug: "buenos-aires" },
    { name: "Lima", slug: "lima" },
    { name: "Munich", slug: "munich" },
    { name: "Budapest", slug: "budapest" },
    { name: "Seoul", slug: "seoul" },
    { name: "Brussels", slug: "brussels" },
    { name: "Zurich", slug: "zurich" },
    { name: "Mexico City", slug: "mexico-city" },
    { name: "New Delhi", slug: "new-delhi" },
    { name: "Cairo", slug: "cairo" },
    { name: "Mecca", slug: "mecca" },
    { name: "Riyadh", slug: "riyadh" },
    { name: "Kuala Lumpur", slug: "kuala-lumpur" },
    { name: "Montreal", slug: "montreal" },
    { name: "Washington D.C.", slug: "washington-dc" },
    { name: "Philadelphia", slug: "philadelphia" },
    { name: "Austin", slug: "austin" },
    { name: "Houston", slug: "houston" },
    { name: "Dallas", slug: "dallas" },
    { name: "Atlanta", slug: "atlanta" },
    { name: "Denver", slug: "denver" },
    { name: "Phoenix", slug: "phoenix" },
    { name: "San Antonio", slug: "san-antonio" },
    { name: "Edinburgh", slug: "edinburgh" },
    { name: "Glasgow", slug: "glasgow" },
    { name: "Krakow", slug: "krakow" },
    { name: "Moscow", slug: "moscow" },
    { name: "Warsaw", slug: "warsaw" },
    { name: "Marrakech", slug: "marrakech" },
    { name: "Johannesburg", slug: "johannesburg" },
    { name: "Bologna", slug: "bologna" },
    { name: "Lyon", slug: "lyon" },
    { name: "Quebec City", slug: "quebec-city" },
    { name: "Sapporo", slug: "sapporo" },
    { name: "Taipei", slug: "taipei" },
    { name: "Luxor", slug: "luxor" },
    { name: "Cusco", slug: "cusco" },
    { name: "Bogotá", slug: "bogota" },
    { name: "Quito", slug: "quito" },
    { name: "La Paz", slug: "la-paz" },
    { name: "Seville", slug: "seville" },
    { name: "Córdoba", slug: "cordoba" },
    { name: "Granada", slug: "granada" },
    { name: "Belgrade", slug: "belgrade" },
    { name: "Sofia", slug: "sofia" },
    { name: "Skopje", slug: "skopje" },
    { name: "Bordeaux", slug: "bordeaux" },
    { name: "Bruges", slug: "bruges" },
    { name: "Antwerp", slug: "antwerp" },
    { name: "Ghent", slug: "ghent" },
    { name: "Nantes", slug: "nantes" },
    { name: "Providence", slug: "providence" },
    { name: "Riga", slug: "riga" },
    { name: "Addis Ababa", slug: "addis-ababa" },
    { name: "Kathmandu", slug: "kathmandu" },
    { name: "Chiang Mai", slug: "chiang-mai" },
    { name: "Vientiane", slug: "vientiane" },
    { name: "Amman", slug: "amman" },
    { name: "Tehran", slug: "tehran" },
    { name: "Yerevan", slug: "yerevan" },
    { name: "Tbilisi", slug: "tbilisi" },
    { name: "Almaty", slug: "almaty" },
    { name: "Astana", slug: "astana" },
    { name: "Mashhad", slug: "mashhad" },
    { name: "Shiraz", slug: "shiraz" },
    { name: "Tabriz", slug: "tabriz" },
    { name: "Isfahan", slug: "isfahan" },
    { name: "Bangalore", slug: "bangalore" },
    { name: "Hyderabad", slug: "hyderabad" },
    { name: "Jaipur", slug: "jaipur" },
    { name: "Lucknow", slug: "lucknow" },
    { name: "Varanasi", slug: "varanasi" },
    { name: "Patna", slug: "patna" },
    { name: "Kanpur", slug: "kanpur" },
    { name: "Delhi", slug: "delhi" },
    { name: "Pune", slug: "pune" },
    { name: "Ahmedabad", slug: "ahmedabad" },
    { name: "Indore", slug: "indore" },
    { name: "Bhopal", slug: "bhopal" },
    { name: "Chengdu", slug: "chengdu" },
    { name: "Xi'an", slug: "xian" },
    { name: "Beijing", slug: "beijing" },
    { name: "Chongqing", slug: "chongqing" },
    { name: "Wuhan", slug: "wuhan" },
    { name: "Nanjing", slug: "nanjing" },
    { name: "Hangzhou", slug: "hangzhou" },
    { name: "Suzhou", slug: "suzhou" },
    { name: "Kunming", slug: "kunming" },
    { name: "Changsha", slug: "changsha" },
    { name: "Zhengzhou", slug: "zhengzhou" },
    { name: "Harbin", slug: "harbin" },
    { name: "Shenyang", slug: "shenyang" },
    { name: "Urumqi", slug: "urumqi" },
    { name: "Hohhot", slug: "hohhot" },
    { name: "Lhasa", slug: "lhasa" },
    { name: "Thimphu", slug: "thimphu" },
    { name: "Ulaanbaatar", slug: "ulaanbaatar" },
    { name: "Harare", slug: "harare" },
    { name: "Lusaka", slug: "lusaka" },
    { name: "Kampala", slug: "kampala" },
    { name: "Bishkek", slug: "bishkek" },
    { name: "Samarkand", slug: "samarkand" },
    { name: "Bukhara", slug: "bukhara" },
    { name: "Goiania", slug: "goiania" },
    { name: "Brasilia", slug: "brasilia" },
    { name: "Belo Horizonte", slug: "belo-horizonte" },
    { name: "Medellin", slug: "medellin" },
    { name: "Cali", slug: "cali" },
    { name: "Asuncion", slug: "asuncion" },
    { name: "Rosario", slug: "rosario" },
    { name: "Arequipa", slug: "arequipa" },
    { name: "Tucuman", slug: "tucuman" },
    { name: "Manaus", slug: "manaus" },
    { name: "Campo Grande", slug: "campo-grande" },
    { name: "San Salvador", slug: "san-salvador" },
    { name: "Tegucigalpa", slug: "tegucigalpa" },
    { name: "Managua", slug: "managua" },
    { name: "Guatemala City", slug: "guatemala-city" },
    { name: "San Jose Costa Rica", slug: "san-jose-costa-rica" },
    { name: "San Pedro Sula", slug: "san-pedro-sula" },
    { name: "Port au Prince", slug: "port-au-prince" },
    { name: "Kingston", slug: "kingston" },
    { name: "Santo Domingo", slug: "santo-domingo" },
    { name: "Raleigh", slug: "raleigh" },
    { name: "Columbus", slug: "columbus" },
    { name: "Indianapolis", slug: "indianapolis" },
    { name: "Kansas City", slug: "kansas-city" },
    { name: "Oklahoma City", slug: "oklahoma-city" },
    { name: "Memphis", slug: "memphis" },
    { name: "Nashville", slug: "nashville" },
    { name: "Detroit", slug: "detroit" },
    { name: "Cleveland", slug: "cleveland" },
    { name: "Pittsburgh", slug: "pittsburgh" },
    { name: "Cincinnati", slug: "cincinnati" },
    { name: "Louisville", slug: "louisville" },
    { name: "Minneapolis", slug: "minneapolis" },
    { name: "St. Paul", slug: "st-paul" },
    { name: "Madison", slug: "madison" },
    { name: "Milwaukee", slug: "milwaukee" },
    { name: "Buffalo", slug: "buffalo" },
    { name: "Rochester", slug: "rochester" },
    { name: "Syracuse", slug: "syracuse" },
    { name: "Albany", slug: "albany" },
    { name: "Toledo", slug: "toledo" },
    { name: "Sacramento", slug: "sacramento" },
    { name: "Portland", slug: "portland" },
    { name: "Salt Lake City", slug: "salt-lake-city" },
    { name: "Albuquerque", slug: "albuquerque" },
    { name: "El Paso", slug: "el-paso" },
    { name: "Tucson", slug: "tucson" },
    { name: "Fresno", slug: "fresno" },
    { name: "Bakersfield", slug: "bakersfield" },
    { name: "San Bernardino", slug: "san-bernardino" },
    { name: "Riverside", slug: "riverside" },
    { name: "Palm Springs", slug: "palm-springs" },
    { name: "Boise", slug: "boise" },
    { name: "Spokane", slug: "spokane" },
    { name: "Tacoma", slug: "tacoma" },
    { name: "Eugene", slug: "eugene" },
    { name: "Salem", slug: "salem" },
    { name: "Hartford", slug: "hartford" },
    { name: "Springfield", slug: "springfield" },
    { name: "Worcester", slug: "worcester" },
    { name: "Akron", slug: "akron" },
    { name: "Dayton", slug: "dayton" },
    { name: "Lexington", slug: "lexington" },
    { name: "Knoxville", slug: "knoxville" },
    { name: "Chattanooga", slug: "chattanooga" },
    { name: "Birmingham", slug: "birmingham" },
    { name: "Montgomery", slug: "montgomery" },
    { name: "Little Rock", slug: "little-rock" },
    { name: "Jackson", slug: "jackson" },
    { name: "Shreveport", slug: "shreveport" },
    { name: "Lafayette", slug: "lafayette" },
    { name: "Tulsa", slug: "tulsa" },
    { name: "Des Moines", slug: "des-moines" },
    { name: "Omaha", slug: "omaha" },
    { name: "Lincoln", slug: "lincoln" },
    { name: "Fargo", slug: "fargo" },
    { name: "Sioux Falls", slug: "sioux-falls" },
    { name: "Rapid City", slug: "rapid-city" },
    { name: "Grand Rapids", slug: "grand-rapids" },
    { name: "Lansing", slug: "lansing" },
    { name: "Flint", slug: "flint" },
    { name: "Peoria", slug: "peoria" },
    { name: "Rockford", slug: "rockford" },
    { name: "Fort Wayne", slug: "fort-wayne" },
    { name: "Evansville", slug: "evansville" },
    { name: "St. Louis", slug: "st-louis" },
    { name: "Kansas City Kansas", slug: "kansas-city-kansas" },
    { name: "Overland Park", slug: "overland-park" },
    { name: "Wichita", slug: "wichita" },
    { name: "Norman", slug: "norman" },
    { name: "Amarillo", slug: "amarillo" },
    { name: "Lubbock", slug: "lubbock" },
    { name: "Plano", slug: "plano" },
    { name: "Irving", slug: "irving" },
    { name: "Arlington", slug: "arlington" },
    { name: "San Jose California", slug: "san-jose-california" },
    { name: "San Mateo", slug: "san-mateo" },
    { name: "Palo Alto", slug: "palo-alto" },
    { name: "Sunnyvale", slug: "sunnyvale" },
    { name: "Mountain View", slug: "mountain-view" },
    { name: "Santa Clara", slug: "santa-clara" },
    { name: "Stockton", slug: "stockton" },
    { name: "Modesto", slug: "modesto" },
    { name: "Reno", slug: "reno" },
    { name: "Carson City", slug: "carson-city" },
    { name: "Las Cruces", slug: "las-cruces" },
    { name: "Flagstaff", slug: "flagstaff" },
    { name: "Santa Fe", slug: "santa-fe" },
    { name: "Cheyenne", slug: "cheyenne" },
    { name: "Billings", slug: "billings" },
    { name: "Helena", slug: "helena" },
    { name: "Great Falls", slug: "great-falls" },
    { name: "Bismarck", slug: "bismarck" },
    { name: "Pierre", slug: "pierre" },
    { name: "Colorado Springs", slug: "colorado-springs" },
    { name: "Aurora Colorado", slug: "aurora-colorado" },
    { name: "Fort Collins", slug: "fort-collins" },
    { name: "Greeley", slug: "greeley" },
    { name: "Provo", slug: "provo" },
    { name: "Orem", slug: "orem" },
    { name: "Ogden", slug: "ogden" },
    { name: "Boulder", slug: "boulder" },
    { name: "Chandler", slug: "chandler" },
    { name: "Scottsdale", slug: "scottsdale" },
    { name: "Mesa", slug: "mesa" },
    { name: "Glendale", slug: "glendale" },
    { name: "Gilbert", slug: "gilbert" },
    { name: "Tempe", slug: "tempe" },
    { name: "Aurora Illinois", slug: "aurora-illinois" },
    { name: "Naperville", slug: "naperville" },
    { name: "Joliet", slug: "joliet" },
    { name: "Columbia Missouri", slug: "columbia-missouri" },
    { name: "Jefferson City", slug: "jefferson-city" },
    { name: "Fayetteville Arkansas", slug: "fayetteville-arkansas" },
    { name: "Fort Smith", slug: "fort-smith" },
    { name: "Cedar Rapids", slug: "cedar-rapids" },
    { name: "Davenport", slug: "davenport" },
    { name: "Sioux City", slug: "sioux-city" },
    { name: "Wichita Falls", slug: "wichita-falls" },
    { name: "Midland", slug: "midland" },
    { name: "Odessa", slug: "odessa" },
    { name: "College Station", slug: "college-station" },
    { name: "Waco", slug: "waco" },
    { name: "McAllen", slug: "mcallen" },
    { name: "Laredo", slug: "laredo" },
    { name: "San Angelo", slug: "san-angelo" },
    { name: "Tyler", slug: "tyler" },
    { name: "Huntsville", slug: "huntsville" },
    { name: "Tuscaloosa", slug: "tuscaloosa" },
    { name: "Macon", slug: "macon" },
    { name: "Augusta Georgia", slug: "augusta-georgia" },
    { name: "Athens Georgia", slug: "athens-georgia" },
    { name: "Gainesville", slug: "gainesville" },
    { name: "Tallahassee", slug: "tallahassee" },
    { name: "Frankfurt", slug: "frankfurt" },
    { name: "Cologne", slug: "cologne" },
    { name: "Düsseldorf", slug: "dusseldorf" },
    { name: "Stuttgart", slug: "stuttgart" },
    { name: "Leipzig", slug: "leipzig" },
    { name: "Dresden", slug: "dresden" },
    { name: "Nuremberg", slug: "nuremberg" },
    { name: "Essen", slug: "essen" },
    { name: "Dortmund", slug: "dortmund" },
    { name: "Bonn", slug: "bonn" },
    { name: "Hanover", slug: "hanover" },
    { name: "Kassel", slug: "kassel" },
    { name: "Mainz", slug: "mainz" },
    { name: "Mannheim", slug: "mannheim" },
    { name: "Karlsruhe", slug: "karlsruhe" },
    { name: "Augsburg", slug: "augsburg" },
    { name: "Magdeburg", slug: "magdeburg" },
    { name: "Erfurt", slug: "erfurt" },
    { name: "Lille", slug: "lille" },
    { name: "Toulouse", slug: "toulouse" },
    { name: "Montpellier", slug: "montpellier" },
    { name: "Grenoble", slug: "grenoble" },
    { name: "Clermont-Ferrand", slug: "clermont-ferrand" },
    { name: "Turin", slug: "turin" },
    { name: "Bergamo", slug: "bergamo" },
    { name: "Verona", slug: "verona" },
    { name: "Padua", slug: "padua" },
    { name: "Parma", slug: "parma" },
    { name: "Modena", slug: "modena" },
    { name: "Brescia", slug: "brescia" },
    { name: "Ljubljana", slug: "ljubljana" },
    { name: "Zagreb", slug: "zagreb" },
    { name: "Sarajevo", slug: "sarajevo" },
    { name: "Podgorica", slug: "podgorica" },
    { name: "Pristina", slug: "pristina" },
    { name: "Tirana", slug: "tirana" },
    { name: "Vilnius", slug: "vilnius" },
    { name: "Kaunas", slug: "kaunas" },
    { name: "Minsk", slug: "minsk" },
    { name: "Chisinau", slug: "chisinau" },
    { name: "Brno", slug: "brno" },
    { name: "Ostrava", slug: "ostrava" },
    { name: "Kosice", slug: "kosice" },
    { name: "Cluj-Napoca", slug: "cluj-napoca" },
    { name: "Timisoara", slug: "timisoara" },
    { name: "Brasov", slug: "brasov" },
    { name: "Wroclaw", slug: "wroclaw" },
    { name: "Poznan", slug: "poznan" },
    { name: "Katowice", slug: "katowice" },
    { name: "Lodz", slug: "lodz" },
];
